### PR TITLE
Fix: make sure org-tree-to-indirect-buffer replace the current buffer

### PR DESCRIPTION
**Pull request by yqrashawn**
----

#

### CODE REVIEW

**Comment by alphapapa** [comment]
The purpose of that function is to return a buffer, not to affect how windows are displayed.  If you are experiencing a bug or undesired behavior, please file an issue and describe it.

**Comment by yqrashawn** [comment]
Sorry I didn't explain the change.

If `org-indirect-buffer-display` is set to `other-window`, which is the default setting, `org-tree-to-indirect-buffer` won't open the desired org buffer which gets from `(org-now--marker)`.

And the rest functions will run on the buffer where user call `org-now`.

You can reproduce this by 
1. setting `org-indirect-buffer-display` to `other-window`
2. set org-now-location to a list longer than 1
3. call `org-now`

**Comment by alphapapa** [comment]
Thanks, I've pushed a fix that seems to work.  Please let me know if it works for you.

**Comment by yqrashawn** [comment]
Thanks. It works great!

**Pull request closed without merging**
